# Generated by Django 6.0.3 on 2026-03-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='claim_proofs/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.claim')),
            ],
        ),
    ]
