# Generated by Django 6.0.3 on 2026-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
