# Generated by Django 6.0.3 on 2026-03-30 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_claim_is_cleared_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='items.item'),
        ),
    ]
